import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { createUserWithEmailAndPassword, onAuthStateChanged, type User } from "firebase/auth";
import { api, type CertificateMeta } from "./api";
import { auth } from "./firebase";
import { config, isConfigured } from "./config";
import { hashFile, isAuthorizedWallet, issueOnChain, readCertificate, revokeOnChain, setUploaderOnChain, wallet } from "./blockchain";
import { login, logout, roleOf } from "./auth";
import type { Address } from "viem";

type Notice = { kind: "error" | "success"; text: string } | null;
const cidUrl = (cid: string) => `${import.meta.env.VITE_IPFS_GATEWAY_URL || "https://gateway.pinata.cloud/ipfs"}/${cid}`;
const explorer = (tx: string) => `${config.explorerUrl}/tx/${tx}`;
const short = (value: string) => value ? `${value.slice(0, 8)}…${value.slice(-6)}` : "—";
const secureId = () => `CERT-${crypto.getRandomValues(new Uint32Array(3)).reduce((value, part) => value + part.toString(36), "").toUpperCase()}`;
const copy = (text: string) => navigator.clipboard.writeText(text);

function Shell({ children }: { children: React.ReactNode }) { return <><header><Link className="brand" to="/"><span>◇</span> Certificate Verification</Link><nav><Link to="/verify">Verify</Link><Link to="/portal">Workspace</Link></nav></header>{children}<footer>© 2026 Certificate Verification. All rights reserved by Trushant Rathod.</footer></>; }
function NoticeBox({ notice }: { notice: Notice }) { return notice ? <p className={`notice ${notice.kind}`}>{notice.text}</p> : null; }
function Loading({ label = "Checking the registry…" }: { label?: string }) { return <div className="loading"><i />{label}</div>; }

function Home() { return <Shell><main className="home"><section className="hero"><p className="eyebrow">CERTIFICATE AUTHENTICITY, PROVEN</p><h1>Verify every certificate.<br /><em>Trust every credential.</em></h1><p className="lead">A tamper-evident certificate registry with free public verification on Ethereum Sepolia.</p><div className="actions"><Link className="button primary" to="/verify">Verify certificate</Link><Link className="button" to="/portal">Issue certificate</Link></div></section><section className="proof" aria-label="Certificate verification path"><div className="certificate-card"><span>Certificate</span><b>VERIFIED</b><small>Credential ID · C-2026-…</small></div><div className="path"><b>SHA-256 hash</b><i>↓</i><b>Blockchain record</b><i>↓</i><b className="verified">✓ Verified</b></div></section><section className="features"><article><b>Byte-perfect proof</b><p>A one-byte alteration changes the SHA-256 hash and fails verification.</p></article><article><b>Public by default</b><p>Recipients verify an ID, file, or QR link without a login, wallet, or payment.</p></article><article><b>Revocation, not deletion</b><p>Historical records stay visible while revoked credentials are clearly marked.</p></article></section></main></Shell>; }

function Verify() {
  const { certificateId } = useParams(); const [id, setId] = useState(certificateId || ""); const [file, setFile] = useState<File>(); const [checking, setChecking] = useState(Boolean(certificateId)); const [result, setResult] = useState<{ meta?: CertificateMeta; state: "valid" | "revoked" | "invalid" | "missing"; reason?: string }>();
  const verify = async (event?: FormEvent) => { event?.preventDefault(); setChecking(true); setResult(undefined); try {
    const hash = file ? await hashFile(file) : undefined; const response = hash ? await api.findByHash(hash) : await api.publicCertificate(id.trim()); const meta = response.certificate;
    if (!meta) return setResult({ state: "missing", reason: "No certificate metadata matches that ID or document hash." });
    const chain = await readCertificate(meta.certificateId);
    if (!chain.issuedAt || chain.issuedAt === 0n) return setResult({ meta, state: "missing", reason: "This ID is not present in the blockchain registry." });
    if (chain.documentHash.toLowerCase() !== meta.documentHash.toLowerCase() || (hash && hash.toLowerCase() !== chain.documentHash.toLowerCase())) return setResult({ meta, state: "invalid", reason: "The uploaded document hash does not match the immutable blockchain record." });
    setResult({ meta, state: chain.revoked ? "revoked" : "valid" });
  } catch (error) { setResult({ state: "invalid", reason: error instanceof Error ? error.message : "Verification failed." }); } finally { setChecking(false); } };
  useEffect(() => { if (certificateId) void verify(); }, [certificateId]);
  return <Shell><main className="page narrow"><p className="eyebrow">PUBLIC VERIFICATION</p><h2>Verify a credential</h2><p className="muted">Use an ID, upload the original certificate, or open its QR link.</p><form className="verify-form" onSubmit={verify}><label>Certificate ID<input value={id} onChange={(e) => { setId(e.target.value); setFile(undefined); }} placeholder="CERT-…" /></label><span className="or">or</span><label className="file">Upload PDF or image<input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={(e) => { setFile(e.target.files?.[0]); setId(""); }} /><b>{file?.name || "Choose original certificate"}</b></label><button className="button primary" disabled={checking || (!id && !file)}>{checking ? "Verifying…" : "Verify"}</button></form>{checking && <Loading label={file ? "Hashing document and checking blockchain…" : "Checking blockchain record…"} />}{result && <VerificationResult result={result} />}</main></Shell>;
}
function VerificationResult({ result }: { result: { meta?: CertificateMeta; state: "valid" | "revoked" | "invalid" | "missing"; reason?: string } }) { const m = result.meta; return <section className={`result ${result.state}`}><div className="result-title"><b>{result.state === "valid" ? "✓ Valid certificate" : result.state === "revoked" ? "! Certificate revoked" : result.state === "missing" ? "? Certificate not found" : "× Verification failed"}</b><p>{result.reason || (result.state === "valid" ? "The file and record match the immutable blockchain entry." : "This credential remains on-chain but is no longer valid.")}</p></div>{m && <><dl><dt>Certificate ID</dt><dd>{m.certificateId}<button onClick={() => copy(m.certificateId)}>Copy</button></dd><dt>Recipient</dt><dd>{m.recipientName}</dd><dt>Credential</dt><dd>{m.credential}</dd><dt>Issuer</dt><dd>{m.organization}</dd><dt>Issued</dt><dd>{m.issueDate}</dd><dt>Status</dt><dd>{result.state.toUpperCase()}</dd><dt>Document hash</dt><dd className="mono">{short(m.documentHash)}<button onClick={() => copy(m.documentHash)}>Copy</button></dd><dt>IPFS CID</dt><dd><a href={cidUrl(m.cid)} target="_blank" rel="noreferrer">{short(m.cid)}</a></dd><dt>Issuer wallet</dt><dd className="mono">{short(m.issuerWallet)}</dd><dt>Transaction</dt><dd><a href={explorer(m.transactionHash)} target="_blank" rel="noreferrer">View on explorer ↗</a></dd></dl><img className="qr" alt={`QR code for ${m.certificateId}`} src={`https://api.qrserver.com/v1/create-qr-code/?size=132x132&data=${encodeURIComponent(`${config.publicUrl}/verify/${m.certificateId}`)}`} /></>}</section>; }

function LoginPage() { const navigate = useNavigate(); const [notice, setNotice] = useState<Notice>(null); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); try { await login(String(data.get("email")), String(data.get("password"))); navigate("/portal"); } catch (error) { setNotice({ kind: "error", text: error instanceof Error ? error.message : "Sign in failed." }); } }; return <Shell><main className="page auth"><p className="eyebrow">SECURE WORKSPACE</p><h2>Sign in</h2><form onSubmit={submit}><label>Email<input required name="email" type="email" /></label><label>Password<input required name="password" type="password" /></label><button className="button primary">Sign in</button></form><p className="muted">Don't have an account? <Link to="/register">Create account</Link></p><NoticeBox notice={notice} /></main></Shell>; }

function RegisterPage() { const navigate = useNavigate(); const [notice, setNotice] = useState<Notice>(null); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); const password = String(data.get("password")); const confirm = String(data.get("confirmPassword")); if (password.length < 6) return setNotice({ kind: "error", text: "Password must be at least 6 characters." }); if (password !== confirm) return setNotice({ kind: "error", text: "Passwords do not match." }); try { if (!auth) throw new Error("Firebase is not configured."); await createUserWithEmailAndPassword(auth, String(data.get("email")), password); setNotice({ kind: "success", text: "Account created. Redirecting to sign in…" }); setTimeout(() => navigate("/login"), 700); } catch (error) { setNotice({ kind: "error", text: error instanceof Error ? error.message.replace("Firebase: Error (auth/", "").replace(").", "") : "Could not create account." }); } }; return <Shell><main className="page auth"><p className="eyebrow">GET STARTED</p><h2>Create account</h2><form onSubmit={submit}><label>Email<input required name="email" type="email" autoComplete="email" /></label><label>Password<input required name="password" type="password" autoComplete="new-password" minLength={6} /></label><label>Confirm password<input required name="confirmPassword" type="password" autoComplete="new-password" minLength={6} /></label><button className="button primary">Create account</button></form><p className="muted">Already have an account? <Link to="/login">Sign in</Link></p><NoticeBox notice={notice} /></main></Shell>; }

function Portal() { const [user, setUser] = useState<User | null>(auth?.currentUser || null); const [role, setRole] = useState<string>(); const [ready, setReady] = useState(Boolean(!auth)); useEffect(() => { if (!auth) return; return onAuthStateChanged(auth, async (next) => { setUser(next); setRole(next ? await roleOf(next) : undefined); setReady(true); }); }, []); if (!ready) return <Shell><main className="page"><Loading /></main></Shell>; if (!auth) return <Shell><main className="page"><h2>Firebase setup required</h2><p>Add the public Firebase variables to enable authentication.</p></main></Shell>; if (!user) return <Navigate to="/login" replace />; if (role !== "admin" && role !== "uploader") return <Shell><main className="page"><h2>Account pending</h2><p>Your Firebase account needs an <code>admin</code> or <code>uploader</code> custom role before it can access this workspace.</p><button className="button" onClick={() => logout()}>Sign out</button></main></Shell>; return <Shell><main className="page workspace"><div className="workspace-head"><div><p className="eyebrow">{role.toUpperCase()} WORKSPACE</p><h2>{role === "admin" ? "Registry control" : "Issue credentials"}</h2><p className="muted">Signed in as {user.email}</p></div><button className="button" onClick={() => logout()}>Sign out</button></div>{role === "admin" ? <Admin /> : <Uploader />}</main></Shell>; }

function Uploader() { const [notice, setNotice] = useState<Notice>(null); const [busy, setBusy] = useState(false); const [certificates, setCertificates] = useState<CertificateMeta[]>([]); const refresh = () => api.certificates().then((v) => setCertificates(v.certificates)).catch(() => {}); useEffect(() => { refresh(); }, []); const issue = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = e.currentTarget; const data = new FormData(form); const file = data.get("file") as File; if (!file?.size) return setNotice({ kind: "error", text: "Choose a certificate PDF or image." }); setBusy(true); setNotice(null); try { const { account } = await wallet(); if (!await isAuthorizedWallet(account)) throw new Error("This connected wallet is not an authorized uploader."); const documentHash = await hashFile(file); const id = secureId(); const { cid } = await api.upload(file); const { tx } = await issueOnChain(id, documentHash, cid); const certificate: CertificateMeta = { certificateId: id, documentHash, cid, issuerWallet: account, transactionHash: tx, recipientName: String(data.get("recipientName")), recipientEmail: String(data.get("recipientEmail") || ""), credential: String(data.get("credential")), organization: String(data.get("organization")), issueDate: String(data.get("issueDate")), expiryDate: String(data.get("expiryDate") || ""), description: String(data.get("description") || ""), status: "valid" }; await api.saveCertificate(certificate); setNotice({ kind: "success", text: `Certificate ${id} is issued and ready to verify.` }); form.reset(); refresh(); } catch (error) { setNotice({ kind: "error", text: error instanceof Error ? error.message : "Issuance failed." }); } finally { setBusy(false); } };
  const revoke = async (id: string) => { if (!confirm(`Revoke ${id}? This cannot be undone.`)) return; try { await revokeOnChain(id); await api.revoke(id); setNotice({ kind: "success", text: "Certificate revoked." }); refresh(); } catch (e) { setNotice({ kind: "error", text: e instanceof Error ? e.message : "Revocation failed." }); } };
  return <><section className="panel"><h3>Issue a certificate</h3><p className="muted">Preparing → Hashing → IPFS → Blockchain → Confirming → Ready</p><form className="issue-grid" onSubmit={issue}><label>Recipient name<input required name="recipientName" /></label><label>Recipient email<input name="recipientEmail" type="email" /></label><label>Course / credential<input required name="credential" /></label><label>Organization / issuer<input required name="organization" /></label><label>Issue date<input required name="issueDate" type="date" /></label><label>Expiry date<input name="expiryDate" type="date" /></label><label className="wide">Description<textarea name="description" rows={2} /></label><label className="wide">Certificate file<input required name="file" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" /></label><button className="button primary" disabled={busy}>{busy ? "Issuing…" : "Connect wallet & issue"}</button></form><NoticeBox notice={notice} /></section><CertificateTable certificates={certificates} onRevoke={revoke} /></>; }

function Admin() { const [notice, setNotice] = useState<Notice>(null); const [users, setUsers] = useState<{ uid: string; name: string; email: string; walletAddress: string; active: boolean }[]>([]); const [certificates, setCertificates] = useState<CertificateMeta[]>([]); const refresh = () => { api.uploaders().then((v) => setUsers(v.users)).catch((e) => setNotice({ kind: "error", text: e.message })); api.certificates().then((v) => setCertificates(v.certificates)).catch(() => {}); }; useEffect(() => { refresh(); }, []); const add = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = e.currentTarget; const data = new FormData(form); const item = { name: String(data.get("name")), email: String(data.get("email")), walletAddress: String(data.get("walletAddress")) as Address, active: true }; try { await setUploaderOnChain(item.walletAddress, true); await api.saveUploader(item); setNotice({ kind: "success", text: "Uploader authorized on-chain and in Firebase." }); form.reset(); refresh(); } catch (error) { setNotice({ kind: "error", text: error instanceof Error ? error.message : "Could not add uploader." }); } };
  const toggle = async (u: { name: string; email: string; walletAddress: string; active: boolean }) => { try { await setUploaderOnChain(u.walletAddress as Address, !u.active); await api.saveUploader({ ...u, active: !u.active }); setNotice({ kind: "success", text: `${u.name} ${u.active ? "deactivated" : "reactivated"}.` }); refresh(); } catch (e) { setNotice({ kind: "error", text: e instanceof Error ? e.message : "Update failed." }); } };
  const stats = useMemo(() => ({ total: certificates.length, valid: certificates.filter((c) => c.status === "valid").length, revoked: certificates.filter((c) => c.status === "revoked").length, uploaders: users.filter((u) => u.active).length }), [certificates, users]); return <><section className="stats">{Object.entries(stats).map(([label, value]) => <div key={label}><b>{value}</b><span>{label}</span></div>)}</section><section className="panel"><h3>Authorize uploader</h3><p className="muted">The user must have already registered with Firebase. This writes their authorization to both Sepolia and Firebase.</p><form className="issue-grid compact" onSubmit={add}><label>Name<input name="name" required /></label><label>Email<input name="email" type="email" required /></label><label>Wallet address<input name="walletAddress" placeholder="0x…" required pattern="0x[a-fA-F0-9]{40}" /></label><button className="button primary">Authorize uploader</button></form><NoticeBox notice={notice} /></section><section className="panel"><h3>Uploaders</h3>{users.length ? <div className="list">{users.map((u) => <div key={u.uid}><span><b>{u.name}</b><small>{u.email} · {short(u.walletAddress)}</small></span><button className="button small" onClick={() => toggle(u)}>{u.active ? "Deactivate" : "Reactivate"}</button></div>)}</div> : <p className="muted">No uploaders yet.</p>}</section><CertificateTable certificates={certificates} /></>; }

function CertificateTable({ certificates, onRevoke }: { certificates: CertificateMeta[]; onRevoke?: (id: string) => void }) { return <section className="panel"><h3>Certificates</h3>{certificates.length ? <div className="table-wrap"><table><thead><tr><th>ID</th><th>Recipient</th><th>Credential</th><th>Status</th><th /></tr></thead><tbody>{certificates.map((c) => <tr key={c.certificateId}><td><Link to={`/verify/${c.certificateId}`}>{c.certificateId}</Link></td><td>{c.recipientName}</td><td>{c.credential}</td><td><span className={`status ${c.status}`}>{c.status}</span></td><td>{onRevoke && c.status === "valid" && <button className="text-button danger" onClick={() => onRevoke(c.certificateId)}>Revoke</button>}</td></tr>)}</tbody></table></div> : <p className="muted">No certificates have been issued.</p>}</section>; }

export default function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/verify" element={<Verify />} /><Route path="/verify/:certificateId" element={<Verify />} /><Route path="/login" element={<LoginPage />} /><Route path="/register" element={<RegisterPage />} /><Route path="/portal" element={<Portal />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
